// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znilfkwojxkmbuwjmjmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuaWxma3dvanhrbWJ1d2ptam13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDg2NzksImV4cCI6MjA2OTIyNDY3OX0.9OF3NeplqwGhVErmSHEaTXHjZau9BsPP2zAscob83iE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});